---
#################
# MANUAL BUILDS #
#################
# name: path/config.*

###############
# AUTO BUILDS #
###############
# From https://github.com/Poeschl/Hassio-Addons
# Those are the addon path filters used in the workflows to determine which addon needs to be build.
# name: slug/filename ; could be slug/config.* for all files
addons_updater: addons_updater/config.*
fireflyiii_fints_importer: fireflyiii_fints_importer/config.*
guacd: guacd/config.*
omada: omada/config.*
paperless_ngx: paperless_ngx/config.*
plex_meta_manager: plex_meta_manager/config.*
scrutiny_fa: scrutiny_fa/config.*
spotweb: spotweb/config.*
tdarr: tdarr/config.*
webtop: webtop/config.*
webtop_kde: webtop_kde/config.*
webtrees: webtrees/config.*
zoneminder: zoneminder/config.*
