# AUTO BUILDS #
# From https://github.com/Poeschl/Hassio-Addons
# name: slug/filename ; could be slug/config.* for all files
addons_updater: addons_updater/config.* # Image : yes # Image : yes
arpspoof: arpspoof/config.*
bazarr: bazarr/config.*
bitwarden: bitwarden/config.*
booksonic_air: booksonic_air/config.*
cloudcommander: cloudcommander/config.*
code-server: code-server/config.*
elasticsearch: elasticsearch/config.*
emby: emby/config.*
enedisgateway2mqtt: enedisgateway2mqtt/config.*
enedisgateway2mqtt_dev: enedisgateway2mqtt_dev/config.*
filebrowser: filebrowser/config.*
fireflyiii: fireflyiii/config.*
fireflyiii_data_importer: fireflyiii_data_importer/config.*
fireflyiii_fints_importer: fireflyiii_fints_importer/config.* # Image : yes # Image : yes
flaresolverr: flaresolverr/config.*
flexget: flexget/config.*
gazpar2mqtt: gazpar2mqtt/config.*
grav: grav/config.*
guacd: guacd/config.*
inadyn: inadyn/config.*
jackett: jackett/config.*
jellyfin: jellyfin/config.*
joal: joal/config.*
joplin: joplin/config.*
lidarr: lidarr/config.*
mealie: mealie/config.*
mylar3: mylar3/config.*
nextcloud: nextcloud/config.*
nzbget: nzbget/config.*
omada: omada/config.* # Image : yes # Image : yes
ombi: ombi/config.*
organizr: organizr/config.*
overseerr: overseerr/config.* # Image : yes
paperless_ngx: paperless_ngx/config.*
papermerge: papermerge/config.*
photoprism: photoprism/config.*
piwigo: piwigo/config.*
plex: plex/config.*
plex_meta_manager: plex_meta_manager/config.* # Image : yes # Image : yes
portainer: portainer/config.*
prowlarr: prowlarr/config.*
qbittorrent: qbittorrent/config.*
radarr: radarr/config.*
readarr: readarr/config.*
requestrr: requestrr/config.*
resiliosync: resiliosync/config.*
scrutiny: scrutiny/config.*
scrutiny_fa: scrutiny_fa/config.* # Image : yes # Image : yes
sonarr: sonarr/config.*
spotweb: spotweb/config.* # Image : yes # Image : yes
tandoor_recipes: tandoor_recipes/config.*
tdarr: tdarr/config.* # Image : yes # Image : yes
teamspeak: teamspeak/config.*
transmission: transmission/config.*
ubooquity: ubooquity/config.*
webtop: webtop/config.*
webtop_kde: webtop_kde/config.* # Image : yes # Image : yes
webtrees: webtrees/config.* # Image : yes # Image : yes
wger: wger/config.*
whoogle: whoogle/config.*
xteve: xteve/config.*
zoneminder: zoneminder/config.* # Image : yes # Image : yes
