---
###############
# AUTO BUILDS #
###############
# From https://github.com/Poeschl/Hassio-Addons
# Those are the addon path filters used in the workflows to determine which addon needs to be build.
# name: slug/filename ; could be slug/config.* for all files
all: */config.*
addons_updater: addons_updater/config.*
fireflyiii_fints_importer: fireflyiii_fints_importer/config.*
guacd: guacd/config.*
omada: omada/config.*
paperless_ngx: paperless_ngx/config.*
plex_meta_manager: plex_meta_manager/config.*
scrutiny_fa: scrutiny_fa/config.*
spotweb: spotweb/config.*
tdarr: tdarr/config.*
webtop: webtop/config.*
webtop_kde: webtop_kde/config.*
webtrees: webtrees/config.*
zoneminder: zoneminder/config.*

#################
# MANUAL BUILDS #
#################
#arpspoof: arpspoof/config.json
#bazarr: bazarr/config.*
#bitwarden: bitwarden/config.*
#booksonic-air: booksonic-air/config.*
#cloudcommander: cloudcommander/config.*
#code-server: code-server/config.*
#elasticsearch: elasticsearch/config.*
#emby: emby/config.*
#enedisgateway2mqtt: enedisgateway2mqtt/config.*
#enedisgateway2mqtt: enedisgateway2mqtt/config.*
#filebrowser: filebrowser/config.*
#firefly iii: firefly iii/config.*
#firefly iii data importer: firefly iii data importer/config.*
#flaresolverr: flaresolverr/config.*
#flexget: flexget/config.*
#gazpar2mqtt: gazpar2mqtt/config.*
#grav: grav/config.*
#inadyn: inadyn/config.*
#jackett: jackett/config.*
#jellyfin: jellyfin/config.*
#joal: joal/config.*
#mealie: mealie/config.*
#mylar3: mylar3/config.*
#nextcloud ocr: nextcloud ocr/config.*
#nzbget: nzbget/config.*
#ombi: ombi/config.*
#organizr: organizr/config.*
#paperless ng: paperless ng/config.*
#papermerge: papermerge/config.*
#photoprism: photoprism/config.*
#piwigo: piwigo/config.*
#plex: plex/config.*
#portainer: portainer/config.*
#prowlarr: prowlarr/config.*
#qbittorrent: qbittorrent/config.*
#radarr: radarr/config.*
#readarr: readarr/config.*
#requestrr: requestrr/config.*
#resioliosync: resioliosync/config.*
#scrutiny: scrutiny/config.*
#sonarr: sonarr/config.*
#tandoor recipes: tandoor recipes/config.*
#teamspeak: teamspeak/config.*
#transmission: transmission/config.*
#ubooquity: ubooquity/config.*
#webtrees: webtrees/config.*
#wger: wger/config.*
#whoogle-search: whoogle-search/config.*
#xteve: xteve/config.*
