---
build_from:
  aarch64: ghcr.io/hassio-addons/debian-base/aarch64:latest
  amd64: ghcr.io/hassio-addons/debian-base/amd64:latest
  armv7: ghcr.io/hassio-addons/debian-base/armv7:latest
codenotary:
  signer: alexandrep.github@gmail.com
