---
###########################
###########################
## Markdown Linter rules ##
###########################
###########################

# Linter rules doc:
# - https://github.com/DavidAnson/markdownlint
#
# Note:
# To comment out a single error:
#   <!-- markdownlint-disable -->
#   any violations you want
#   <!-- markdownlint-restore -->
#

###############
# Rules by id #
###############
MD013: false # Maximum 80 characters per line
MD041: false # First-line-heading/first-line-h1

#################
# Rules by tags #
#################
blank_lines: false # Error on blank lines
