arch:
- aarch64
- amd64
codenotary: alexandrep.github@gmail.com
description: Personal Relationship Manager
devices:
- "/dev/dri"
- "/dev/dri/card0"
- "/dev/dri/card1"
- "/dev/dri/renderD128"
- "/dev/vchiq"
- "/dev/video10"
- "/dev/video11"
- "/dev/video12"
- "/dev/video13"
- "/dev/video14"
- "/dev/video15"
- "/dev/video16"
- "/dev/ttyUSB0"
- "/dev/sda"
- "/dev/sdb"
- "/dev/sdc"
- "/dev/sdd"
- "/dev/sde"
- "/dev/sdf"
- "/dev/sdg"
- "/dev/nvme"
- "/dev/nvme0n1p1"
- "/dev/nvme0n1p2"
- "/dev/nvme0n1p3"
- "/dev/nvme1n1p1"
- "/dev/nvme1n1p2"
- "/dev/nvme1n1p3"
- "/dev/nvme2n1p1"
- "/dev/nvme2n1p2"
- "/dev/nvme3n1p3"
- "/dev/mmcblk"
- "/dev/fuse"
- "/dev/sda1"
- "/dev/sdb1"
- "/dev/sdc1"
- "/dev/sdd1"
- "/dev/sde1"
- "/dev/sdf1"
- "/dev/sdg1"
- "/dev/sda2"
- "/dev/sdb2"
- "/dev/sdc2"
- "/dev/sdd2"
- "/dev/sde2"
- "/dev/sdf2"
- "/dev/sdg2"
- "/dev/sda3"
- "/dev/sdb3"
- "/dev/sda4"
- "/dev/sdb4"
- "/dev/sda5"
- "/dev/sda6"
- "/dev/sda7"
- "/dev/sda8"
- "/dev/nvme0"
- "/dev/nvme1"
- "/dev/nvme2"
environment: {
  "APP_TRUSTED_PROXIES": "*",
  "APP_ENV": "production",
  "APP_DEBUG": "false"
}
image: ghcr.io/alexbelgium/monica-{arch}
init: false
options: {
  "database": "sqlite"
}
map:
  - type: addon_config
    read_only: false
name: Monica
ports:
  8080/tcp: 8181
ports_description:
  8080/tcp: webui
schema: {
  "database": "list(sqlite|MariaDB_addon|Mysql_external)",
  "APP_KEY": "str?",
  "DB_DATABASE": "str?",
  "DB_HOST": "str?",
  "DB_PASSWORD": "str?",
  "DB_PORT": "int?",
  "DB_USERNAME": "str?"
}
services:
- mysql:want
slug: monica
url: https://github.com/alexbelgium/hassio-addons/tree/master/monica
version: test11
webui: "[PROTO:ssl]://[HOST]:[PORT:8080]"
