# yamllint disable rule:line-length
---
name: Convert crlf to lf

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  crlf_to_lf:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Run script file
      run: |
        rm README.md
        cp .README.j2 README.md
        ADDONSLINE=$(sed -n '/%%ADDONS_LIST%%/=' README.md)
        sed -i "$ADDONSLINEd" README.md
        for f in *; do
          # $f is an addon directory
          if [ -f "$f"/config.json ]; then
            [ $(jq '.[arch].aarch64' $f/config.json") ] && sed -i "$ADDONSLINEi ![aarch64][aarch64-badge]" README.md   
            [ $(jq '.[arch].amd64' $f/config.json") ] && sed -i "$ADDONSLINEi ![amd64][amd64-badge]" README.md   
            [ $(jq '.[arch].armv7' $f/config.json") ] && sed -i "$ADDONSLINEi ![armv7][armv7-badge]" README.md   
            [ $(jq '.ingress' $f/config.json") ] && sed -i "$ADDONSLINEi ![ingress][ingress-badge]" README.md   
            [ $(jq '.codenotary' $f/config.json") ] && sed -i "$ADDONSLINEi ![Signed][signed-badge]" README.md         
            [ $(jq '.version' $f/config.json") ] && sed -i "$ADDONSLINEi ![version][version-badge]" README.md         
            sed -i "$ADDONSLINEi - [$(jq '.name' $f/config.json")]($f/) : jq '.description' $f/config.json" README.md
          fi
        done
      shell: bash
    - name: Create New Pull Request If Needed
      uses: peter-evans/create-pull-request@v3
      with:
        title: "Github bot : crlf removed"
        branch-suffix: timestamp
        commit-message: "Github bot : crlf removed"


{% for addon in addons %} : {{ addon.description }}
### &#10003; [{{ addon.name }}][addon-{{ addon.target }}]

![Latest Version][{{ addon.target }}-version-shield]
![Supports armhf Architecture][{{ addon.target }}-armhf-shield]
![Supports armv7 Architecture][{{ addon.target }}-armv7-shield]
![Supports aarch64 Architecture][{{ addon.target }}-aarch64-shield]
![Supports amd64 Architecture][{{ addon.target }}-amd64-shield]
![Supports i386 Architecture][{{ addon.target }}-i386-shield]

{% endfor %}
