name: Lint / Syntax checks
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - uses: hadolint/hadolint-action@v1.6.0
      with:
        dockerfile: Dockerfile

  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: ↩️ Checkout
        uses: actions/checkout@v2

      - name: 📂 Detect chanced files
        id: filter
        uses: dorny/paths-filter@v2.9.0
        with:
          list-files: 'shell'
          filters: |
            shell:
              - '**/*.sh'
              - '**/cont-init.d/*'
              - '**/services.d/*'
      - name: 🔎 Run ShellCheck
        if: steps.filter.outputs.shell == 'true'
        uses: ludeeus/action-shellcheck@1.1.0
        with:
          additional_files: ${{ steps.filter.outputs.shell_files }}

  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - name: ↩️ Checkout
        uses: actions/checkout@v2

      - name: 🔎 Run markdownlint
        uses: nosborn/github-action-markdown-cli@v1.1.1
        with:
          files: .
