# yamllint disable rule:line-length
# shellcheck disable=SC2043
---
name: Check PR Build
on:
  pull_request:
    types: [opened, edited]
    branches:
      - master

jobs:
  enable-auto-merge:
    name: 🤖 Auto merge release PR
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'auto-merge')
    steps:
      - name: Enable auto-merge
        uses: reitermarkus/automerge@v2.1.2
        with:
          token: ${{ secrets.Auto_Merge }}
          merge-method: squash
