# yamllint disable rule:line-length
# shellcheck disable=SC2043
---
name: PR automerge
on:
  pull_request:
    types: [ labeled ]

jobs:
  enable-auto-merge:
    name: 🤖 Auto merge release PR
    runs-on: ubuntu-latest
    if: ${{ github.event.label.name == 'auto-merge' }}
    steps:
      - name: Enable auto-merge
        uses: reitermarkus/automerge@v2.1.2
        with:
          token: ${{ secrets.Auto_Merge }}
          merge-method: squash
