# yamllint disable rule:line-length
# shellcheck disable=SC2043
---
name: automerge
on:
  pull_request_review:
    types:
      - submitted
  issue_comment:
    types: created
  check_suite:
    types:
      - completed
  status: {}
jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Add the automerge label
        if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/automerge') }}
        uses: actions/github-script@v4
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['automerge']
            })
      - name: Merge PR
        if: steps.check_comment.outputs.automerge
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.payload.issue.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            await github.pulls.merge({
              owner,
              repo,
              pull_number: prNumber,
              merge_method: 'merge'
            });
            console.log(`PR #${prNumber} merged successfully.`);
