# yamllint disable rule:line-length
---
name: Make scripts executable

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  chmod_execute:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Run script file
      id: chmod
      run: |
        find . -name *.sh -print0 | xargs -0 chmod +x && \
        grep -rl '#!/' . | xargs chmod +x
      shell: bash
      - name: Create New Pull Request If Needed
        if: steps.calibre.outputs.markdown != ''
        uses: peter-evans/create-pull-request@v4
        with:
          title: "Github bot : script chmod"
          branch-suffix: timestamp
          commit-message: "Github bot : script chmod"
          body: ${{ steps.calibre.outputs.markdown }}
