# yamllint disable rule:line-length
---
name: Weekly lint config

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  build:
    name: Add-on configuration
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v2
      - name: 🚀 Run Home Assistant Add-on Lint
        uses: frenck/action-addon-linter@v1
        with:
          path: "./*/"
