# yamllint disable rule:line-length
---
name: Convert crlf to lf

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  sort_json:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Run script file
      id: sort
      run: |
        echo "Converting crlf to lf"
        grep -rl '\r' ./hassio-addons | xargs sed -i 's/\r//'
      shell: bash
    - name: Create New Pull Request If Needed
      uses: peter-evans/create-pull-request@v3
      with:
        title: "Github bot : crlf removed"
        branch-suffix: timestamp
        commit-message: "Github bot : crlf removed"
