# yamllint disable rule:line-length
---
name: Convert crlf to lf

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  crlf_to_lf:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    - name: Run script file
      id: sort
      run: |
        git clone t-regx/crlf
        cd crlf
        pip install -r requirements/requirements.txt
        python setup.py install
        cd ..
        cd hassio-addons
        crlf -R . --to lf
      shell: bash
    - name: Create New Pull Request If Needed
      uses: peter-evans/create-pull-request@v5
      with:
        title: "Github bot : crlf to lf"
        branch-suffix: timestamp
        commit-message: "Github bot : crlf to lf"
