# yamllint disable rule:line-length
---
name: Generate README

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  README_updater:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Run script file
      run: |
        rm README.md
        cp .README.j2 README.md
        ADDONSLINE=$(sed -n '/%%ADDONS_LIST%%/=' README.md)
        sed -i "/**ADDONS_LIST%%/d" README.md
        for f in *; do
          # $f is an addon directory
          if [ -f "$f"/config.json ]; then
            echo "Project $f"
            sed -i "$ADDONSLINE"'{G;}' README.md
            [[ $(jq '.arch[]' "$f/config.json") == *"aarch64"* ]] && sed -i "$ADDONSLINE"'i ![aarch64][aarch64-badge]' README.md || true
            [[ $(jq '.arch[]' "$f/config.json") == *"amd64"* ]] && sed -i "$ADDONSLINE"'i ![amd64][amd64-badge]' README.md || true
            [[ $(jq '.arch[]' "$f/config.json") == *"armv7"* ]] && sed -i "$ADDONSLINE"'i ![armv7][armv7-badge]' README.md || true
            [[ $(jq '.ingress' "$f/config.json") == "true" ]] && sed -i "$ADDONSLINE"'i ![ingress][ingress-badge]' README.md || true
            sed -i "$ADDONSLINE"'i ![Version](https://img.shields.io/badge/dynamic/json?label=Version&query=%24.version&url=https%3A%2F%2Fraw.githubusercontent.com%2Falexbelgium%2Fhassio-addons%2Fmaster%2F'"$f"'%2Fconfig.json)' README.md || true
            NAME=$(jq -r '.name' $f/config.json)
            DESCRIPTION=$(jq -r '.description' $f/config.json)
            sed -i "$ADDONSLINE"'i &#10003; ['"$NAME"']('"$f"'/) : '"$DESCRIPTION" README.md
            sed -i "$ADDONSLINE"'i' README.md
            sed -i "$ADDONSLINE"'a' README.md
          fi
        done
      shell: bash
    - name: Commit if needed
      uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
